### ISSUE TITLE
extra space so private key is empty ?

### ISSUE THREAD

**Issue by franck34** [ericvicenti/ssh-keygen#11]
hi

line 94
```
key = key.substring(0, key.lastIndexOf(" \n"));
```

On my side (linux) i have to remove the extra space before \n to have the private key in the callback when destroy:true.

If i i don't do that, key is empty.

What do you think ? 

Thank you !

**Comment by ericvicenti** [comment]
I used to use this thing on linux, so I'm not sure what changed.

But the requested change seems reasonable! If you submit a PR, I'll merge it and cut a new minor version :-D

**Comment by franck34** [comment]
Lol. Going crazy troubleshooting ssh-keygen and ssh2 mscdex module. 

No clear yet. I'll give you feedback later. Thanks for quick answer ;)

**Comment by franck34** [comment]
Done

https://github.com/ericvicenti/ssh-keygen/pull/12

**Comment by franck34** [comment]
@ericvicenti do you think it's possible you can merge, bump version and publish a new npm today ?

**Comment by franck34** [comment]
@ericvicenti ping :)

**Comment by ericvicenti** [comment]
Apologies for the glacial response times in this repository
