### ISSUE TITLE
Outdated underscore dependency reported with High security

### ISSUE THREAD

**Issue by jaspenlind** [ericvicenti/ssh-keygen#24]
=== npm audit security report ===                        

Some vulnerabilities require your attention to resolve
Visit https://go.npm.me/audit-guide for additional guidance

High  Arbitrary Code Execution
Package: underscore
atched in: >=1.12.1
Dependency of: ssh-keygen
Path: ssh-keygen > underscore 
More info: https://npmjs.com/advisories/1674

**Comment by micalevisk** [comment]
as this repo feels abandoned, I've forked and published it under [`@micalevisk/ssh-keygen`](https://www.npmjs.com/package/@micalevisk/ssh-keygen) package. It doesn't rely on `underscore` anymore. And it has a type definitions file :fire: 

```ts
import keygen from '@micalevisk/ssh-keygen'

keygen({
  comment: 'john@doe.com',
  read: true
}, function (err, out) { // Optional callback. Will return a Promise if not provided
  if (err !== undefined) return console.log('There was a problem : ' + err)
  console.log('Done generating key pairs')
  console.log(out?.key)
  console.log(out?.pubKey)
})
```

<details>

![image](https://user-images.githubusercontent.com/13461315/151904001-ca89cbfb-0caa-4482-9861-e79208944a90.png)

![image](https://user-images.githubusercontent.com/13461315/151904012-2c9c248e-0925-4453-8789-37ec7d286e05.png)

</details>

---

Also, I'm planning to do the following (later):

- [x] refactor the whole code (using modern JS and support only node v12+)
- [ ] validate options properly (and in an [really async manner](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#why-would-that-be-allowed))
- [ ] copy fixes from PRs that are open in this repo
- [ ] write automated tests
- [x] try to fix open Issues on this repo


_(I'll update this message accordingly)_.

**Comment by ericvicenti** [comment]
Apologies for the late response and "High security" warning. There is no security impact here as we don't use `underscore`'s template function.

And wow, I must have been 10 years dumber when I wrote this library, because it literally imports underscore for `_.isUndefined`, LOL
