### ISSUE TITLE
Destroy-option defaults to true instead of false

### ISSUE THREAD

**Issue by GeraldWodni** [ericvicenti/ssh-keygen#4]
Hi,

I was wondering where the keyfiles went, because the documentation says:
`destroy, destroy the key files once they have been read, defaults false`
but in ssh-keygen.js in line #102 destroy defaults to true:
`if(_.isUndefined(opts.destroy)) opts.destroy = true;`

Please change either the documentation or the readme.

Thanks, Gerald

**Comment by ericvicenti** [comment]
Sorry about the issue! PR would be accepted for this

**Comment by GeraldWodni** [comment]
Actually there are already two pending PRs (#7 and #8)  who fix the issue ;)

**Comment by ericvicenti** [comment]
Fix released in 0.4.0
